version: "3.3"
services:
  stub-ldap:
    image: stub-ldap
    build:
      context: .
    environment:
      USERS_CONFIG_FILE: '/config/users.json'
      LDAP_PORT: 389
      LDAP_BIND_DN: CN=Administrator,CN=Users,DC=example,DC=local
      LDAP_BIND_PASSWORD: Some+Bind+Pw123!
      LDAP_SUFFIX: DC=example,DC=local
      LDAP_DOMAIN: example.local
      LDAP_USERS_BASE_DN: CN=Users,DC=example,DC=local
    volumes:
    - ./config:/config
    ports:
      - 389:389